//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDWithTwoTables.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExampleDbModel : DbContext
    {
        public ExampleDbModel()
            : base("name=ExampleDbModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarDetail> CarDetails { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }

        public System.Data.Entity.DbSet<CRUDWithTwoTables.Models.MultipleClass> MultipleClasses { get; set; }
    }
}
